### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Davegb** [SCAI-BIO/STEP#1]
Hi, there!

I'd like to know if you have a requirements.txt with all the versions of the libraries, so we can use your tool, please. We tried setting up the environment on our own, but we're getting the following error:

ModuleNotFoundError: No module named 'pytorch_lightning.core.memory'

We already have the Pytorch Lightning package installed, so we think it's an issue with the version.

Thanks!

**Comment by maestro4** [comment]
Hey there,

is this issue still active?

**Comment by Davegb** [comment]
> Hey there,
> 
> is this issue still active?

They never replied. I had to ditch it.

**Comment by maestroe** [comment]
Sorry, just saw this issue. Somehow didn't get the notification through Github.

**Comment by Davegb** [comment]
It's fine. I still think there should exist a requirements.txt file for future users.

**Comment by maestroe** [comment]
You're right. I actually have a Conda env file, will push it.
